name: DevPlat Chat Extension CI
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
    - name: Install dependencies
      run: npm install
    - name: Build and package extension
      run: npx vsce package
    - name: Upload VSIX
      uses: actions/upload-artifact@v3
      with:
        name: devplat-agent-extension
        path: devplat-agent-*.vsix